version: "3.1"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: superpass
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres:
